import Head from 'next/head'

import React, { useState, useEffect } from "react"

import Header from "../components/Header"
import InputTodo from "../components/InputTodo"
import TodosList from "../components/TodosList";
import { v4 as uuidv4 } from "uuid";


export default function TodoContainer() {
  const TodoContainer = () => {

      const [todos, setTodos] = useState(getInitialTodos())
    
      useEffect(() => {
        // storing todos items
        const temp = JSON.stringify(todos)
        localStorage.setItem("todos", temp)
      }, [todos])
    
      function getInitialTodos() {
        // getting stored items
        const temp = localStorage.getItem("todos")
        const savedTodos = JSON.parse(temp)
        return savedTodos || [] 
      }
     
      const handleChange = id => {
        setTodos(prevState => prevState.map((todo) => {
          if (todo.id === id) {
            return {
              ...todo, completed: !todo.completed
            }
          }
          return todo
        }))
      }
    
      const delTodo = id => {
        setTodos([
          ...todos.filter(todo => {
            return todo.id !== id
          }),
        ])
      };
    
      const addTodoItem = title => {
        const newTodo = {    
          id: uuidv4(),    
          title: title,    
          completed: false  
        };
        setTodos([...todos, newTodo])
      };
    
      const setUpdate = (updatedTitle, id) => {
        setTodos(
          todos.map(todo => {
            if (todo.id === id) {
              todo.title = updatedTitle
            }
            return todo
          })
        )
      }
    
      return (   
        <>
          <Head />
            <title>Next.js TODO APP</title>
            <meta name="description" content="Generated by create next app"/>
            <link rel="icon" href="/favicon.ico"/>  
          
          <body>
            <noscript>You need to enable JavaScript to run this app.</noscript>
            <div id="__next">
            <React.StrictMode>
              <div className="container">
                <div className="inner">
                  <Header />
                  <InputTodo addTodoProps={addTodoItem} />
                  <TodosList 
                    todos={todos} 
                    handleChangeProps={handleChange} 
                    deleteTodoProps={delTodo}
                    setUpdate ={setUpdate} 
                  />
                </div>
              </div>
            </React.StrictMode>
            </div>
          </body>
        </>
      );
  }
}      